name: 📖 Documentation
description: Suggest an improvement or fix to the documentation of this project
title: "(doc): <Enter title here, leaving the '(doc): ' prefix>"
labels: ["documentation"]

body:
  - type: markdown
    id: disclaimer
    attributes:
      value: |
        ## ⚠️ Disclaimer

        _Thank you for taking the time to create this issue!_

        _Please note that if this is a question, like how to do something or where to find information, please use the_ [Discussions](https://github.com/adam-grant-hendry/widgetry/discussions) _tab instead. We are happy to help you there! (Another good place to ask is_ [StackOverflow (SO)](https://stackoverflow.com/)). This will help maintainers separate concerns and solve issues quickly.

        That said, don't worry about making a mistake. If you think you're dealing with a bug, post it here and we'll work through it with you. We'd rather know than not know 😉!_

  - type: checkboxes
    id: prerequisites
    attributes:
      label: ✅ Prerequisites
      description: |
        By submitting this issue, I agree to the following:
      options:
        - label: |
            I have reviewed the disclaimer above: I am not submitting a general question and believe this to be an actual bug.
          required: true
        - label: |
            I have read and agree to follow this project's [Code of Conduct](https://example.com). I will treat all people respectfully in communications here.
          required: true
        - label: |
            I have searched the [Issues](https://github.com/adam-grant-hendry/widgetry) and [Discussions](https://github.com/adam-grant-hendry/widgetry/discussions) tabs for similar/relevant issues and do not believe this to be a duplicate.
          required: true

  - type: checkboxes
    id: type
    attributes:
      label: Type
      options:
        - label: Content inaccurate
        - label: Content missing
        - label: Hyperlink is broken
        - label: Typo

  - type: input
    id: url
    attributes:
      label: URL
      placeholder: |
        Link to documentation and/or examples where content is inaccurate or lacking...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of what content should be added or fixed...
    validations:
      required: true
