name: ✨ Feature Request
description: Submit a feature request
title: "(feat): <Enter title here, leaving the '(feat): ' prefix>"
labels: ["enhancement"]

body:
  - type: markdown
    id: greeting
    attributes:
      value: |
        _Thank you for taking the time to create this issue!_

        _Please note that if this is a question, like how to do something or where to find information, please use the_ [Discussions](https://github.com/adam-grant-hendry/widgetry/discussions) _tab instead. We are happy to help you there! (Another good place to ask is_ [StackOverflow (SO)](https://stackoverflow.com/)). This will help maintainers separate concerns and solve issues quickly.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: ✅ Prerequisites
      description: |
        By submitting this issue, I agree to the following:
      options:
        - label: |
            I have read and agree to follow this project's [Code of Conduct](https://example.com). I will treat all people respectfully in communications here.
          required: true
        - label: |
            I have searched the [Issues](https://github.com/adam-grant-hendry/widgetry) tracker for similar feature requests.
          required: true
        - label: |
            I will only submit one feature per requests. My idea is one feature.
          required: true

  - type: textarea
    id: description
    attributes:
      label: 💡 Idea
      description: Please describe the feature you would like to be added
      placeholder: |
        * Explain what you would like to do (_include a_ `gist` _link, if appropriate._)
        * Add pseudocode or explain how you envision this working
        * Include screenshots and/or links to similar features existing elsewhere
    validations:
      required: true
